### ISSUE TITLE
Instant crash when switching to hotkey mode

### ISSUE THREAD

**Issue by Vizoplez** [Lyut/BYONDHook#4]
Crash is entirely based on pressing tab or clicking the 'chat' button, Uncertain as to why. May submit a fix PR.

**Comment by Vizoplez** [comment]
This is just one /guaranteed/ crash. There are other random ones that occur as the round progresses. Testing experimental fixes to help stop this.

Seems to be due to command logging so far.

**Comment by Lyut** [comment]
Hey, would you please mind saying which server did you try this on? I can't seem to reproduce the issue neither on Goonstation nor Lifeweb, I've pressed tab and hotkey mode seems to switch on/off without crashing.

99% of crashes are due to the the CommandEvent hook, the command logging indeed on very rare occasions trips on access violations when reading the pointer to the command string retrieved from the EAX register.

**Comment by Vizoplez** [comment]
> Hey, would you please mind saying which server did you try this on? I can't seem to reproduce the issue neither on Goonstation nor Lifeweb, I've pressed tab and hotkey mode seems to switch on/off without crashing.
> 
> 99% of crashes are due to the the CommandEvent hook, the command logging indeed on very rare occasions trips on access violations when reading the pointer to the command string retrieved from the EAX register.

A variety of servers, ranging from Sojourn to Merchantstation, I tried on both the most recent beyond and the version showcased on the github, both crash instantaneously upon hotkey mode being activated.

This also seems to be related to just hotkey mode being activated, because once you do; any subsequent reconnects instantly crash once you get into the server.

**Comment by Lyut** [comment]
I'm sorry, I've just tested Merchantstation on 514.1584 (which is currently unsupported) and it works. Are you using the latest source code with the commandevent "fix"? The compiled dll available in the "releases" section is outdated

**Comment by Lyut** [comment]
I can confirm this issue and I'm investigating, very weird.
I'm also focused at the moment on the 514.1584 update which somehow broke the CommandEvent hook and returns an invalid pointer even though nothing inside that function in byondcore.dll has changed. They are also now elevating dreamseeker.exe privileges, I suggest staying on 1583 as of now.

**Comment by Lyut** [comment]
Hello, please try upgrading to BYOND 514.1584 and compiling commit 22d0d5501136cd680098e8d30cd1edb6d92d7857 and see if it fixes your issue.

Best Regards

**Comment by Lyut** [comment]
commit 0cc0de6f74dbb33957830c7855f200c187a8b437 seems to finally get rid of the issue, including the rare occasional crashing. Please, let me know how it goes

**Comment by Vizoplez** [comment]
> commit [0cc0de6](https://github.com/Lyut/BYONDHook/commit/0cc0de6f74dbb33957830c7855f200c187a8b437) seems to finally get rid of the issue, including the rare occasional crashing. Please, let me know how it goes

Will try.

**Comment by Vizoplez** [comment]
![image](https://user-images.githubusercontent.com/65188584/172063160-2caafdac-62b5-4bc2-8f9b-69334dc626f8.png)
Past the occasional bug (this), everything seems to now work fine.

Will re-open if new issues arise.

**Comment by Lyut** [comment]
Alright, sorry to mention that but I believe that is not really a BYONDHook "bug", there's some servers where I can't understand why, multiple child processes of dreamseeker are started (depending on the server, sometimes only on the first join), then the parent process is terminated. The child processes don't have visible windows except for the last one which shows up the game, but it causes the console windows to be opened. I'm pushing a new update soon, by changing "AllocConsole = 1" to 0 in the config.ini file, you will be able to suppress the console window so that these won't show up anymore.

**Comment by Vizoplez** [comment]
> Alright, sorry to mention that but I believe that is not really a BYONDHook "bug", there's some servers where I can't understand why, multiple child processes of dreamseeker are started (depending on the server, sometimes only on the first join), then the parent process is terminated. The child processes don't have visible windows except for the last one which shows up the game, but it causes the console windows to be opened. I'm pushing a new update soon, by changing "AllocConsole = 1" to 0 in the config.ini file, you will be able to suppress the console window so that these won't show up anymore.

Year later, can confirm this was a security measure to try and destroy people using CID spoofers (They forcefully relaunch your game to try and catch on-inject DLLs to see if your CID changes between each instance).
